version: "3"
services:
  ubuntu:
    build:
      context: .
      args:
        GIT_USER: ${GIT_USER}
        GIT_EMAIL: ${GIT_EMAIL}
    privileged: true
    volumes:
      - .:/root/toytcp
    tty: true
